### ISSUE TITLE
[Bug]: The share button is "stuck" on the bottom right of the screen.

### ISSUE THREAD

**Issue by Hidden-Warden** [Hidden-Warden/Marmit65#52]
### Describe the bug

The share button should be at the bottom of the web page, yet it does not move with the page

**Comment by Hidden-Warden** [comment]
Or at least be smaller

**Comment by Ryse93** [comment]
Mais c'est fait exprès

**Comment by Hidden-Warden** [comment]
Ouais mais sur mobile ça prend beaucoup de place..

**Comment by Ryse93** [comment]
bah sur mobile je l'ai virée, vu que c'est avec le hover et que on peut pas sur mobile
